// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PratikCodeFirstBasic.Data;

#nullable disable

namespace PratikCodeFirstBasic.Migrations
{
    [DbContext(typeof(PatikaFirstDbContext))]
    partial class PatikaFirstDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PratikCodeFirstBasic.Data.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Rating")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Games", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tatile çık",
                            Platform = "PC",
                            Rating = 10m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Evlen",
                            Platform = "PlayStation",
                            Rating = 1m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Saygınlık kazan",
                            Platform = "Xbox",
                            Rating = 7m
                        });
                });

            modelBuilder.Entity("PratikCodeFirstBasic.Data.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Movies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Genre = "Aksiyon",
                            ReleaseYear = 2012,
                            Title = "Tatile çık"
                        },
                        new
                        {
                            Id = 2,
                            Genre = "Comedy",
                            ReleaseYear = 2024,
                            Title = "Evlen"
                        },
                        new
                        {
                            Id = 3,
                            Genre = "Drama",
                            ReleaseYear = 2014,
                            Title = "Saygınlık kazan"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
